### ISSUE TITLE
Plugin Icon not appearing in UE5.3.2

### ISSUE THREAD

**Issue by jwax33** [Kranox21/ChannelMachine#3]
I installed ChannelMachine from the launcher and enabled the plugin in UE5.3.2 (and restarted) but the little multi-colored gear icon that's supposed to appear on the plugin bar so you can use the plugin is not there.  I'm not sure how to proceed.

![image](https://github.com/Kranox21/ChannelMachine/assets/16256444/d4fc3c43-5571-4024-853d-ce4d8ad62a5c)

**Comment by Kranox21** [comment]
Hi @jwax33
Thanks for posting the issue on GitHub

To start with, by any chance could the icon be hiding away in Window tab at the top? Sometimes Unreal can be weird how it handles the toolbar icons.

![image](https://github.com/Kranox21/ChannelMachine/assets/11131166/1e941d05-31ac-4e4c-bf52-beae1283a451)

If not showing up are you running Windows 64bit Operating System?

If yes running Windows 64bit. Mind checking in the Plugins window again to be sure that Editor Scripting Utilities & Python Editor Script Plugin are both enabled?

![image](https://github.com/Kranox21/ChannelMachine/assets/11131166/389da088-4306-4e42-ba30-4db11a87bc72)
![image](https://github.com/Kranox21/ChannelMachine/assets/11131166/9f17df18-fc78-4112-9446-3a6f11ba516b)

If all that fails will you be able to run the tool from its source location without any errors?

Enable both Engine and Plugin Content
![image](https://github.com/Kranox21/ChannelMachine/assets/11131166/10121fbe-00e2-4901-bffa-1366326ba70d)

Locate path All/Engine/Plugins/Channel Machine Content
![image](https://github.com/Kranox21/ChannelMachine/assets/11131166/5fd0ba9e-a3f5-426a-9f48-b7622d24f7b7)

Right click on Channel Machine and click Run Editor Utility Widget
![image](https://github.com/Kranox21/ChannelMachine/assets/11131166/287b03ac-28b5-474b-acc2-bf35fa966225)

If Channel Machine Editor fails to run, let me know if any errors may have occurred in the Output Log.

**Comment by jwax33** [comment]
Hi Kranox, thanks for the quick response.

I am running Win64 and no, the plugin does not show up in the Window menu.

I do have both editor script utility plugins enabled.

If I locate the blueprint manually in the Engine Plugins folder, I am able to run it as a Utility Widget.  It appears that just the icon and menu entry are missing for some reason.

**Comment by Kranox21** [comment]
Hmm that's strange. If possible, you can send me the zip file containing a few log files, the path under /Project Name/Saved/Logs/ProjectName.log so I can further inspect this.

**Comment by jwax33** [comment]
Sure.  Hope this helps.

**Comment by Kranox21** [comment]
Mind sending it again through GitHub website I think sending attachments through email isn't supported on GitHub.

**Comment by jwax33** [comment]
Here you go.
[Logs.zip](https://github.com/Kranox21/ChannelMachine/files/14227131/Logs.zip)

**Comment by Kranox21** [comment]
Provide fix though latest hotfix update.
